%% position parameters
give_positions;

folder_name = '/Users/apple/ownCloud/Yue/Personal Data/17 Feb/0206';
file_name = 'test_a';

%% initialize

% Creat the window for GUI
global window;
window = figure('Name', 'FID-Freq',...
                'DockControl', 'off',...
                'Units', 'Pixels',...
                'Position', p_window);
            
% Creat axes for fid
global ax_fid;
ax_fid = axes('Parent', window,...
                'Units', 'normalized',...
                'Position', p_ax_fid);
            
% Creat axes for ft
global ax_ft;
ax_ft = axes('Parent', window,...
                'Units', 'normalized',...
                'Position', p_ax_ft);           
            
% Add folder text edit
global folder;
folder = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', folder_name,...
                    'Position', p_folder);  
                
% Add folder text edit label
folder_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Folder:',...
                    'Position', p_fol_lab);  

% Add filename text edit
global filename;
filename = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', file_name,...
                    'Position', p_fname);  

% Add filename text edit label
filename_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Filename:',...
                    'Position', p_fna_lab);  
               
% Add zerofilling text edit label
zerofilling_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Zerofilling:',...
                    'Position', p_zf_lab);  
                
% Add zerofilling option
global zerofilling;
zerofilling = uicontrol('Parent', window,...
                    'Style', 'popupmenu',...
                    'Units', 'normalized',...
                    'String', {'none';'X 2';'X 4';'X 8';'X 16'},...
                    'Position', p_zf); 
 
% Add ft summation text (phase cancelled)
global ft_sum;
ft_sum = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Undertermined',...
                    'Position', p_ft_sum);    

% Add ft summation text label (phase cancelled)
ft_sum_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'FT SUM:',...
                    'Position', p_ft_sum_l); 
                
% Add SNR text
global h_snr;
h_snr = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Undertermined',...
                    'Position', p_snr);

% Add SNR text label
snr_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'SNR:',...
                    'Position', p_snr_lab);
                
% Add Max between cursors text
global spec_max;
spec_max = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Undertermined',...
                    'Position', p_smax);
                
% Add max between cursor text label
spec_max_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Max:',...
                    'Position', p_smax_l);
                
% Add FWHM text
global h_fwhm;
h_fwhm = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Undertermined',...
                    'Position', p_fwhm);
                
% Add max between cursor text label
fwhm_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'FWHM:',...
                    'Position', p_fwhm_l);
                
% Add magnitude integral text
global h_magint;
h_magint = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Undertermined',...
                    'Position', p_magint);
                
% Add max between cursor text label
magint_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Magnitude integral',...
                    'Position', p_magint_l);
%% plot data
                
% read data and plot fid and ft
plot_data = uicontrol('Parent', window,...
                    'Style', 'pushbutton',...
                    'String', 'PLOT!',...
                    'FontSize', 18,...
                    'Units', 'normalized',...
                    'Position', p_rd_data,...
                    'Callback', @plot_callback);
               
%% Add cursors

% Add text edit for fid_cursor
global fid_cursor;
fid_cursor = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '0 2',...
                    'Position', p_fid_cs,...
                    'Callback', {@cursor_callback,ax_fid}); 
                
% Add fid_cursor text edit label
fid_cursor_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Cursor:',...
                    'Position', p_fid_csl); 

% Add fid_chop button       
fid_cursor_chop = uicontrol('Parent', window,...
                    'Style', 'pushbutton',...
                    'String', 'chop',...
                    'FontSize', 12,...
                    'Units', 'normalized',...
                    'Position', p_fid_cscp,...
                    'Callback', @fid_chop_callback);
                
% Add text edit for ft_cursor
global ft_cursor;
ft_cursor = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '3.11e4 3.13e4',...
                    'Position', p_ft_cs,...
                    'Callback', {@cursor_callback,ax_ft}); 
                
% Add ft_cursor text edit label
ft_cursor_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Cursor:',...
                    'Position', p_ft_csl); 

% Add ft_chop button       
ft_cursor_chop = uicontrol('Parent', window,...
                    'Style', 'pushbutton',...
                    'String', 'chop',...
                    'FontSize', 12,...
                    'Units', 'normalized',...
                    'Position', p_ft_cscp,...
                    'Callback', @ft_chop_callback);
                
%% explore axis

% Add text edit for manual fid_Xlim setting
global fid_xlim;
fid_xlim = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '0 1',...
                    'Position', p_fid_xl,...
                    'Callback', {@xlim_callback,ax_fid}); 

% Add fid_xlim text edit label
fid_xlim_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Xlim:',...
                    'Position', p_fid_xl_l); 
                
% Add fid_xlim_reset button
fid_xlim_reset = uicontrol('Parent', window,...
                    'Style', 'pushbutton',...
                    'String', 'reset',...
                    'FontSize', 12,...
                    'Units', 'normalized',...
                    'Position', p_fid_xl_r,...
                    'Callback', {@xreset_callback,ax_fid}); 
                
% Add text edit for manual Xlim_hi setting
global ft_xlim;
ft_xlim = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '3.1e4 3.14e4',...
                    'Position', p_ft_xl,...
                    'Callback', {@xlim_callback,ax_ft}); 
                
% Add ft_xlim text edit label
ft_xlim_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Xlim:',...
                    'Position', p_ft_xl_l); 

% Add ft_xlim_reset button
ft_xlim_reset = uicontrol('Parent', window,...
                    'Style', 'pushbutton',...
                    'String', 'reset',...
                    'FontSize', 12,...
                    'Units', 'normalized',...
                    'Position', p_ft_xl_r,...
                    'Callback', {@xreset_callback,ax_ft}); 
                
% Add text edit for manual fid_ylim setting
global fid_ylim;
fid_ylim = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '-0.5 0.5',...
                    'Position', p_fid_yl,...
                    'Callback', {@ylim_callback,ax_fid}); 

% Add fid_ylim text edit label
fid_ylim_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Ylim:',...
                    'Position', p_fid_yl_l); 
                
% Add fid_ylim_reset button
fid_ylim_reset = uicontrol('Parent', window,...
                    'Style', 'pushbutton',...
                    'String', 'reset',...
                    'FontSize', 12,...
                    'Units', 'normalized',...
                    'Position', p_fid_yl_r,...
                    'Callback', @(h_obj, event) ylim(ax_fid,'auto')); 
                
% Add text edit for manual Xlim_hi setting
ft_ylim = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '0 1e4',...
                    'Position', p_ft_yl,...
                    'Callback', {@ylim_callback,ax_ft}); 
                
% Add ft_xlim text edit label
ft_ylim_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Ylim:',...
                    'Position', p_ft_yl_l); 

% Add ft_xlim_reset button
ft_ylim_reset = uicontrol('Parent', window,...
                    'Style', 'pushbutton',...
                    'String', 'reset',...
                    'FontSize', 12,...
                    'Units', 'normalized',...
                    'Position', p_ft_yl_r,...
                    'Callback', @(h_obj, event) ylim(ax_ft,'auto'));
       
%% phasing

% Add auto phasing button
autophase = uicontrol('Parent', window,...
                    'Style', 'pushbutton',...
                    'String', 'AUTO PHASE',...
                    'FontSize', 12,...
                    'Units', 'normalized',...
                    'Position', p_autoph,...
                    'Callback', @autophase_callback);
                
% Add ft summation text (phase cancelled)
global reft_sum;
reft_sum = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Undertermined',...
                    'Position', p_reft_sum);    

% Add ft summation text label (phase cancelled)
reft_sum_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'REAL SUM:',...
                    'Position', p_reftsuml); 
                
% Add phase text (phase cancelled)
global ph_angle;
ph_angle = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Undertermined',...
                    'Position', p_ph_ang);    

% Add phase angle text label (phase cancelled)
ph_angle_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Phase:',...
                    'Position', p_ph_ang_l); 
                
% Add manual phase text label
ph_angle_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Manual Phase',...
                    'Position', p_ma_ph_l); 
                
% Add manual phase adjust option
global manualphase;
manualphase = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '0',...
                    'Position', p_ma_ph,...
                    'Callback', @manualphase_callback); 

%% filter

% Add filter frequency text edit
global filter_band;
filter_band = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '500 4e5',...
                    'Position', p_ft_bd);
                
% Add filter button
global filter_bt;
filter_bt = uicontrol('Parent', window,...
                    'Style', 'togglebutton',...
                    'String', 'FILTER',...
                    'FontSize', 12,...
                    'Units', 'normalized',...
                    'Position', p_filter,...
                    'Callback', @filter_callback);
                
%% trim

% Add shreshold text edit
global shreshold;
shreshold = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '0.01',...
                    'Position', p_shold);
                
% Add trim button
trim_bt = uicontrol('Parent', window,...
                    'Style', 'togglebutton',...
                    'String', 'TRIM',...
                    'FontSize', 12,...
                    'Units', 'normalized',...
                    'Position', p_trim,...
                    'Callback', @trim_callback);
                
%% window function
global window_select;
window_select = uicontrol('Parent', window,...
                    'Style', 'popupmenu',...
                    'Units', 'normalized',...
                    'String', {'exponential'; 'hanning';'hamming';'blackman'},...
                    'Position', p_ws);

global wf_bt;
wf_bt = uicontrol('Parent', window,...
                    'Style', 'togglebutton',...
                    'String', 'Windowed',...
                    'FontSize', 12,...
                    'Units', 'normalized',...
                    'Position', p_wf,...
                    'Callback', @wf_callback);
                